apiVersion: v1
kind: Service
metadata:
  name: cloudgarden-service
  labels:
    app: cloudgarden
spec:
  type: NodePort
  selector:
    app: cloudgarden
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Access frontend at <minikube-ip>:30080
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081  # Access backend API at <minikube-ip>:30081
